# Generated by Django 5.2.4 on 2025-08-07 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token_creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
