# Generated by Django 5.2.4 on 2025-08-11 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_usuario_token_creado_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaDenuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_hecho', models.DateField(blank=True, null=True)),
                ('es_anonima', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('enviada', 'Enviada'), ('en revisión', 'En revisión'), ('en proceso', 'En proceso'), ('resuelta', 'Resuelta'), ('cerrada', 'Cerrada')], default='enviada', max_length=20)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='denuncias/evidencias/')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('finalizada_en', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.categoriadenuncia')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BitacoraDenuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='dashboard.denuncia')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('barrio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.barrio')),
            ],
        ),
        migrations.AddField(
            model_name='denuncia',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.ubicacion'),
        ),
        migrations.AddIndex(
            model_name='denuncia',
            index=models.Index(fields=['estado'], name='dashboard_d_estado_592189_idx'),
        ),
        migrations.AddIndex(
            model_name='denuncia',
            index=models.Index(fields=['creada_en'], name='dashboard_d_creada__750887_idx'),
        ),
    ]
