# Generated by Django 5.2.4 on 2025-08-12 21:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_barrio_categoriadenuncia_denuncia_bitacoradenuncia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='fecha_hecho',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
