# Generated by Django 5.1 on 2025-08-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_denuncia_fecha_hecho'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='rechazo_motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='estado',
            field=models.CharField(choices=[('enviada', 'Enviada'), ('en revisión', 'En revisión'), ('en proceso', 'En proceso'), ('resuelta', 'Resuelta'), ('rechazada', 'Rechazada')], default='enviada', max_length=20),
        ),
    ]
