# Generated by Django 5.1 on 2025-09-01 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_denuncia_rechazo_motivo_alter_denuncia_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='resolucion_evidencia',
            field=models.FileField(blank=True, null=True, upload_to='denuncias/resoluciones/'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='resolucion_nota',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='resuelto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias_resueltas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='rechazo_motivo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
