# Generated by Django 5.1 on 2025-09-02 17:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_denuncia_resolucion_evidencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, default='')),
                ('dpi_frente', models.FileField(blank=True, null=True, upload_to='permisos/dpi/')),
                ('dpi_reverso', models.FileField(blank=True, null=True, upload_to='permisos/dpi/')),
                ('evidencia_lugar', models.FileField(blank=True, null=True, upload_to='permisos/evidencia_lugar/')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('cantidad_dias', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('requiere_pmt', models.BooleanField(default=False)),
                ('requiere_conos', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('enviada', 'Enviada'), ('revisada', 'Revisada'), ('aceptada', 'Aceptada'), ('en proceso', 'En proceso'), ('finalizada', 'Finalizada')], default='enviada', max_length=20)),
                ('visible_en_mapa', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.ubicacion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tipo_permiso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.tipopermiso')),
            ],
        ),
        migrations.CreateModel(
            name='BitacoraPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='dashboard.permiso')),
            ],
        ),
        migrations.AddIndex(
            model_name='permiso',
            index=models.Index(fields=['estado'], name='dashboard_p_estado_6cced8_idx'),
        ),
        migrations.AddIndex(
            model_name='permiso',
            index=models.Index(fields=['creado_en'], name='dashboard_p_creado__5935d4_idx'),
        ),
    ]
