# Generated by Django 5.1 on 2025-09-02 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_tipopermiso_permiso_bitacorapermiso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permiso',
            name='cantidad_dias',
        ),
    ]
