# Generated by Django 5.1 on 2025-09-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_permiso_cantidad_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoradenuncia',
            name='actor',
            field=models.CharField(blank=True, choices=[('ciudadano', 'Ciudadano'), ('administrador', 'Administrador'), ('sistema', 'Sistema')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bitacoradenuncia',
            name='cambios',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bitacoradenuncia',
            name='estado_anterior',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bitacoradenuncia',
            name='estado_nuevo',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bitacoradenuncia',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
        migrations.AddField(
            model_name='bitacoradenuncia',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bitacorapermiso',
            name='actor',
            field=models.CharField(blank=True, choices=[('ciudadano', 'Ciudadano'), ('administrador', 'Administrador'), ('sistema', 'Sistema')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bitacorapermiso',
            name='cambios',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bitacorapermiso',
            name='estado_anterior',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bitacorapermiso',
            name='estado_nuevo',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bitacorapermiso',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
        migrations.AddField(
            model_name='bitacorapermiso',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='bitacoradenuncia',
            index=models.Index(fields=['fecha'], name='dashboard_b_fecha_8bc25a_idx'),
        ),
        migrations.AddIndex(
            model_name='bitacorapermiso',
            index=models.Index(fields=['fecha'], name='dashboard_b_fecha_4070fe_idx'),
        ),
    ]
