# Generated by Django 5.1 on 2025-09-14 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_bitacoradenuncia_actor_bitacoradenuncia_cambios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='aceptacion_nota',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='permiso',
            name='aceptado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_aceptados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permiso',
            name='permiso_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='permisos/adjuntos/'),
        ),
    ]
