# Generated by Django 5.1 on 2025-09-14 18:59

import django.utils.timezone
from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_permiso_aceptacion_nota_permiso_aceptado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='comienza_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permiso',
            name='termina_en',
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
    ]
