# Generated by Django 5.2.4 on 2025-09-29 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_permiso_comienza_en_permiso_termina_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('vencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recargo_mora_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.CharField(max_length=120)),
                ('nit', models.CharField(blank=True, default='', max_length=20)),
                ('codigo_catastral', models.CharField(blank=True, default='', max_length=50)),
                ('activa', models.BooleanField(default=True)),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.ubicacion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recargo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='pendiente', max_length=10)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletas', to='dashboard.cuentaservicio')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.periodo')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.tarifa')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('metodo', models.CharField(choices=[('caja', 'Caja'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('online', 'Online')], max_length=20)),
                ('referencia', models.CharField(blank=True, default='', max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='dashboard.cuentaservicio')),
                ('usuario_registra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AplicacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='dashboard.boleta')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='dashboard.pago')),
            ],
        ),
        migrations.CreateModel(
            name='TransaccionOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(default='Recurrente', max_length=50)),
                ('orden_id', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaccion', to='dashboard.pago')),
            ],
        ),
    ]
