# Generated by Django 5.2.4 on 2025-09-29 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_periodo_tarifa_cuentaservicio_boleta_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciononline',
            name='pago',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaccion', to='dashboard.pago'),
        ),
        migrations.AlterUniqueTogether(
            name='boleta',
            unique_together={('cuenta', 'periodo')},
        ),
        migrations.AlterUniqueTogether(
            name='periodo',
            unique_together={('anio', 'mes')},
        ),
        migrations.AddIndex(
            model_name='boleta',
            index=models.Index(fields=['cuenta', 'estado'], name='dashboard_b_cuenta__7d7a71_idx'),
        ),
        migrations.AddIndex(
            model_name='boleta',
            index=models.Index(fields=['periodo'], name='dashboard_b_periodo_5f69c1_idx'),
        ),
        migrations.AddIndex(
            model_name='boleta',
            index=models.Index(fields=['creada_en'], name='dashboard_b_creada__fc27dd_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentaservicio',
            index=models.Index(fields=['usuario'], name='dashboard_c_usuario_a08d36_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentaservicio',
            index=models.Index(fields=['activa'], name='dashboard_c_activa_f9cc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='periodo',
            index=models.Index(fields=['anio', 'mes'], name='dashboard_p_anio_045076_idx'),
        ),
        migrations.AddIndex(
            model_name='transacciononline',
            index=models.Index(fields=['orden_id'], name='dashboard_t_orden_i_c31daf_idx'),
        ),
        migrations.AddIndex(
            model_name='transacciononline',
            index=models.Index(fields=['estado'], name='dashboard_t_estado_71f5be_idx'),
        ),
        migrations.AddConstraint(
            model_name='transacciononline',
            constraint=models.UniqueConstraint(fields=('orden_id',), name='uniq_recurrente_orden_id'),
        ),
    ]
