# Generated by Django 5.2.4 on 2025-09-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_transacciononline_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='recargo_mora_fijo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
