# Generated by Django 5.2.4 on 2025-10-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_tarifa_recargo_mora_fijo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciononline',
            name='orden_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
