# Generated by Django 5.2.4 on 2025-11-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_transacciononline_orden_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='acepta_terminos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='terminos_aceptados_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='terminos_version',
            field=models.CharField(default='v1-2025-11', max_length=20),
        ),
    ]
